### ISSUE TITLE
Provide example about how to use the API?

### ISSUE THREAD

**Issue by haifenghuang** [GJDuck/GC#2]
I've seen the `gc.h`, but cannot figure out how to use them, could you please supply some examples  about how to use the API?

**Comment by GJDuck** [comment]
Basically it is just a `malloc` replacement, so you replace all calls to `malloc()` with `GC_malloc()`.  Since it is a garbage collector, you can also remove all calls to `free()`, or (optionally) replace with calls to `GC_free()`.

I think you might need to manually call `GC_init()` too.  The GC may need help finding "roots", which are global variables that might store pointers.  You can call `GC_root` or `GC_dynamic_root` for this.

There is also a whole bunch of other stuff in `gc.h` but that is mostly for advanced applications so is probably not interesting.

Multi-threaded programs are not supported.  Apart from that, it should work (hopefully).  The project is not nearly the same level of polish as the more famous Boehm collector.  For most serious applications you just want to use the Boehm collector.
